books/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls import url, include
from django.contrib import admin
from resources import BookResource

app_name = 'books'

book_resource = BookResource()

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update_user/$', views.update_user, name='update_user'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'detail'),
    url(r'^(?P<book_id>[0-9]+)/notify/$', views.send_email, name='notify'),
    url(r'^create_book/$', views.create_book, name='create_book'),
    url(r'(?P<pk>[0-9]+)/update_book/$', views.BookUpdate.as_view(), name='update_book'),
    url(r'^(?P<book_id>[0-9]+)/delete_book/$', views.delete_book, name='delete_book'),
    url(r'^charts/$', views.charts, name='charts'),
    url(r'^books/', include(book_resource.urls)),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
    url(r'^', include('books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from books.resources import BookResource

book_resource = BookResource()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
    url(r'^', include('books.urls')),
    url(r'^api/', include(book_resource.urls)),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.urls import reverse
from .choices import *
import re, math
from collections import Counter
import numpy
import numpy.linalg

WORD = re.compile(r'\w+')


class Book(models.Model):
    user = models.ForeignKey(User, default=1)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    publisher = models.CharField(max_length=100)
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)
    sub_category = models.CharField(max_length=30, blank=True)
    cover = models.FileField(blank=True)
    image_url = models.CharField(max_length=300, blank=True)
    condition = models.IntegerField(choices=CONDITION_CHOICES, default=1)
    edition = models.CharField(max_length=30, blank=True)
    cost = models.IntegerField(default=200)
    # seller = models.ForeignKey(User)
    cost = models.IntegerField()
    buy_sell = models.IntegerField(choices=BUY_SELL_ENUM, default=1)

    def get_absolute_url(self):
        return reverse('books:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return (self.title)

    @classmethod
    def get_cosine(cls, vec1, vec2):
        intersection = set(vec1.keys()) & set(vec2.keys())
        numerator = sum([vec1[x] * vec2[x] for x in intersection])

        sum1 = sum([vec1[x] ** 2 for x in vec1.keys()])
        sum2 = sum([vec2[x] ** 2 for x in vec2.keys()])
        denominator = math.sqrt(sum1) * math.sqrt(sum2)

        if not denominator:
            return 0.0
        else:
            return float(numerator) / denominator

    @classmethod
    def text_to_vector(cls, text):
        words = WORD.findall(text)
        return Counter(words)

    @staticmethod
    def nearest_neighbour(self, feature_array):
        distances_and_index = []
        index = 0
        for features in feature_array:
            a = numpy.array((features[0], features[1], features[2], features[3]))
            b = numpy.array((1.0, 1.0, 1.0, self.category))

            dist = numpy.linalg.norm(a - b)
            distances_and_index.append([dist, index])
            index += 1

            distances_and_index.sort()

        return  distances_and_index

    def recommend_books(self):
        other_books = Book.objects.exclude(pk=self.pk).all()
        books = []
        feature_array = []

        for book in other_books:
            books.append(book.__dict__)

        for book in other_books:
            a = Book.text_to_vector(book.author)
            b = Book.text_to_vector(self.author)
            f1 = Book.get_cosine(a, b)
            a = Book.text_to_vector(book.publisher)
            b = Book.text_to_vector(self.publisher)
            f2 = Book.get_cosine(a, b)
            a = Book.text_to_vector(book.sub_category)
            b = Book.text_to_vector(self.sub_category)
            f3 = Book.get_cosine(a, b)
            f4 = book.category
            feature_array.append([float(f1), float(f2), float(f3), float(book.category)])

        recommended_books = Book.nearest_neighbour(self, feature_array)
        resp = []
        print len(recommended_books)
        for book in recommended_books[:4]:
            resp.append(other_books[book[1]])

        return resp

books/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Book
from .choices import *


class BookForm(forms.ModelForm):
	class Meta:
		model = Book
		fields = ['title', 'author', 'publisher', 'edition', 'condition', 'cost', 'category', 'cover', 'buy_sell']


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'password']


class UpdateUserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ['email', 'password']

books/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Permission, User
from django.views.generic import View
from books.models import Book
from .forms import UserForm, BookForm, UpdateUserForm
from django.db.models import Q
import os
import datetime
import smtplib

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def charts(request):
        return render(request, 'books/charts.html')


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'books/login.html')
    else:
        books = Book.objects.filter(user=request.user)
        query = request.GET.get("q")
        if query:
            books = Book.objects.filter(
                Q(title__icontains=query) |
                Q(author__icontains=query),
            ).exclude(user=request.user).distinct()
            return render(request, 'books/search_form.html', {
                'books': books
            })
        else:
            return render(request, 'books/index.html', {'books': books})


class DetailView(generic.DetailView):
    model = Book
    template_name = 'books/detail.html'


def create_book(request):
    if not request.user.is_authenticated():
        return render(request, 'books/login.html')
    else:
        form = BookForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            book = form.save(commit=False)
            book.user = request.user
            book.cover = request.FILES['cover']
            file_type = book.cover.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'book': book,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'books/book_form.html', context)
            book.save()
            return render(request, 'books/detail.html', {'book': book})
        context = {
            "form": form,
        }
        return render(request, 'books/book_form.html', context)


class BookUpdate(UpdateView):
    model = Book
    fields = ['title', 'author', 'publisher', 'edition', 'condition', 'cost', 'category', 'cover']


def update_user(request):
    if not request.user.is_authenticated():
        return render(request, 'books/login.html')
    else:
        form = UpdateUserForm(request.POST or None)
        if form.is_valid():
            edited_user = form.save(commit=False)
            user = request.user
            username = user.username
            password = form.cleaned_data['password']
            user.email = form.cleaned_data['email']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    books = Book.objects.filter(user=request.user)
                    return render(request, 'books/index.html', {'books': books})
        context = {
            "form": form,
        }
        return render(request, 'books/update_user.html', context)


def delete_book(request, book_id):
    book = Book.objects.get(pk=book_id)
    if book.user == request.user:
        book.delete()
    books = Book.objects.filter(user=request.user)
    return render(request, 'books/index.html', {'books': books})


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                books = Book.objects.filter(user=request.user)
                return render(request, 'books/index.html', {'books': books})
    context = {
        "form": form,
    }
    return render(request, 'books/user_form.html', context)


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'books/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                books = Book.objects.filter(user=request.user)
                return render(request, 'books/index.html', {'books': books})
            else:
                return render(request, 'books/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'books/login.html', {'error_message': 'Invalid login'})
    return render(request, 'books/login.html')


def send_email(request, book_id):
    book = Book.objects.get(pk=book_id)
    to_email = str(book.user.email)

    if book.buy_sell == 1:
        subject = "Seller for Book: " + book.title
        message = ("Hey "+str(book.user.email)+",\n\nYour requested book: "+book.title+" is being sold by: "+request.user.email+".")
    else:
        subject = "Buyer for Book: " + book.title
        message = ("Hey "+str(book.user.email)+",\n\nYour book: "+book.title+" is being requested by: "+request.user.email+".")

    s = smtplib.SMTP('smtp.gmail.com', 587)
    s.starttls()
    s.login("noodleportal819@gmail.com", "")  # enter password
    s.sendmail("noodleportal819@gmail.com", to_email, message)
    s.quit()

    return render(request, 'books/index.html')

books/templates/books/base.html
<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8">
	<title>{% block title %}Noodle{% endblock %}</title>
	<!-- Loads the path to your static files -->
	{% load staticfiles %}

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Satisfy" rel='stylesheet' type="text/css" />

	<link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}" />

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">

			<!-- Header -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'books:index' %}">Noodle</a>
			</div>


			<!-- Items -->
			<div class="collapse navbar-collapse" id="topNavBar">
				<ul class='nav navbar-nav'>
					<li class="">
						<a href="{% url 'books:index' %}">
							<span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;My Books
						</a>
					</li>
				</ul>

				<form class="navbar-form navbar-left" role="search" method="get" action="{% url 'books:index' %}">
                <div class="form-group">
                    <input type="text" placeholder="Search by Title, Author" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            	</form>

				<ul class="nav navbar-nav navbar-right">
                    <li class="">
						<a href="{% url 'books:charts' %}">
							<span class="glyphicon glyphicon-signal" aria-hidden="true"></span>&nbsp;Charts
						</a>
					</li>
					<li class="">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;<u>{{ request.user.username }}</u><span class="caret"></span></a>
				        <ul class="dropdown-menu">
				          <li><a href="{% url 'books:update_user' %}">Edit Profile</a></li>
				        </ul>
					</li>
					<li class="">
						<a href="{% url 'books:create_book' %}">
							<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Book
						</a>
					</li>
					<li class="">
						<a href="{% url 'books:logout_user' %}">
							<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
						</a>
					</li>
				</ul>

			</div>

		</div>
	</nav>
{% block body %}
{% endblock %}

</body>
</html>

books/templates/books/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'books:index' %}">Noodle</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'books:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'books:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

books/templates/books/book_form.html
{% extends 'books/base.html' %}
{% block title %}Add a New Book{% endblock %}

{% block body %}
<div class="container-fluid">

	<div class="row">

		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>Add a new Book</h3>
					{% if error_message %}
						<p><strong>{{ error_message }}</strong></p>
					{% endif %}
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'books/form_template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="Submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>

				</div>			
			</div>		
		</div>		
	</div>
	
</div>
{% endblock %}

books/templates/books/detail.html
{% extends 'books/base.html' %}
{% block title %}{{ book }}{% endblock %}

{% block body %}

<div class="container-fluid songs-container">

    <div class="row">

        <div class="col-sm-3 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'books:detail' book.id %}">
                        {% if book.cover %}
                            <img src="{{ book.cover.url }}" class="img-responsive center-block" style="max-height:440px">
                        {% elif book.image_url %}
                            <img src="{{ book.image_url }}" class="img-responsive center-block" style="max-height:440px">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                </div>
            </div>
            <div class="col-sm-12">
            <br>
            <a href="{% url 'books:notify' book_id=book.id%}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon"></span>Notify
                    {% if book.buy_sell == 1%}
                    Buyer
                    {% else %}
                    Seller
                    {% endif %}
                </button>
            </a>
	</div>
        </div>
            <div class="col-sm-9 col-md-9">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Details of the book:</h3><br>
                        <b>Title: &nbsp;</b>{{ book.title }}<br>
                        <b>Author: &nbsp;</b>{{ book.author }}<br>
                        <b>Publisher: &nbsp;</b>{{ book.publisher }}<br>
                        <b>Edition: &nbsp;</b>{{ book.edition }}<br>
                        <b>Condition: &nbsp;</b>{{ book.get_condition_display }}<br>
                        <b>Category: &nbsp;</b>{{ book.get_category_display }}<br><br>
                        <b>Cost: &nbsp;</b>{{ book.cost }}<br>
                        <b>Buy/Sell: &nbsp;</b>{{ book.get_buy_sell_display }}
                    </div>
                </div>   
            </div>
            <div class="col-sm-9 col-md-9">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {% if book.buy_sell == 1%}
                        <h3>Details of the buyer:</h3><br>
                        {% else %}
                        <h3>Details of the seller:</h3><br>
                        {% endif %}
                        <b>Name: &nbsp;</b>{{ book.user.first_name }} {{ book.user.last_name }}<br>
                        <b>Email: &nbsp;</b>{{ book.user.email }}<br>
                    </div>
                </div>   
            </div>
    </div>

    <h2> You may also like... </h2>
        <hr/>
    <div class="row">


        {% for book in book.recommend_books %}
                <div class="col-md-3">
                    <div class="thumbnail">
                        <a href="{% url 'books:detail' book.id %}">
                            {% if book.cover %}
                                <img src="{{ book.cover.url }}" class="img-responsive center-block" style="height:400px">
                            {% elif book.image_url %}
                                <img src="{{ book.image_url }}" class="img-responsive center-block" style="height:400px">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                        <div class="caption">
                            <div style="height: 30px; text-overflow: ellipsis; overflow-y: hidden;"><h4>{{ book.title }}</h4></div>
                            <h6>by {{ book.author }}</h6>
                            <h6>INR {{ book.cost }}</h6>

                            <!-- View Details -->
                            <a href="{% url 'books:detail' book.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                        </div>
                    </div>
                </div>
                {% endfor %}
    </div>

<div>
{% endblock %}

books/templates/books/form_template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

books/templates/books/index.html
{% extends 'books/base.html' %}

{% block body %}

<div class="books-container container-fluid col-sm-6">

    <!-- Books -->
    <div class="row">
        <div class="col-sm-6">
        </div>
            <h2>&nbsp;&nbsp;Buy Orders:</h2>
			<br><br>
			{% for book in books %}
				{% if book.buy_sell == 1 %}
				<div class="col-sm-6 col-md-6">
					<center>
						<div class="thumbnail">
							<a href="{% url 'books:detail' book.id %}">
								<img src="{{ book.cover.url }}" class="img-responsive center-block" style="max-height:220px">
							</a>
							<div class="caption">
								<h4>{{ book.title }}</h4>
								<h6>by {{ book.author }}</h6>
								<h6>INR {{ book.cost }}</h6>

								<!-- View Details -->
								<a href="{% url 'books:detail' book.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

								<!-- Edit Book -->
								<form action="{% url 'books:update_book' book.id %}" method="get" style="display: inline;">
									{% csrf_token %}
									<input type="hidden" name="book_id" value="{{ book.id }}" />
									<button type="submit" class="btn btn-default btn-sm">
										<span class="glyphicon glyphicon-edit"></span>
									</button>
								</form>

								<!-- Delete Book -->
								<form action="{% url 'books:delete_book' book.id %}" method="post" style="display: inline;">
									{% csrf_token %}
									<input type="hidden" name="book_id" value="{{ book.id }}" />
									<button type="submit" class="btn btn-default btn-sm">
										<span class="glyphicon glyphicon-trash"></span>
									</button>
								</form>


							</div>
						</div>
					</center>
				</div>
			{% endif %}
			{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
		{% endfor %}
    </div>
</div>

<div class="books-container container-fluid col-sm-6">

    <!-- Books -->
    <div class="row">
        <div class="col-sm-6">
        </div>
            <h2>&nbsp;&nbsp;Sell Orders:</h2>
			<br><br>
			{% for book in books %}
				{% if book.buy_sell == 2 %}
				<div class="col-sm-6 col-md-6">
					<center>
						<div class="thumbnail">
							<a href="{% url 'books:detail' book.id %}">
								<img src="{{ book.cover.url }}" class="img-responsive center-block" style="max-height:220px">
							</a>
							<div class="caption">
								<h4>{{ book.title }}</h4>
								<h6>by {{ book.author }}</h6>
								<h6>INR {{ book.cost }}</h6>

								<!-- View Details -->
								<a href="{% url 'books:detail' book.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

								<!-- Edit Book -->
								<form action="{% url 'books:update_book' book.id %}" method="get" style="display: inline;">
									{% csrf_token %}
									<input type="hidden" name="book_id" value="{{ book.id }}" />
									<button type="submit" class="btn btn-default btn-sm">
										<span class="glyphicon glyphicon-edit"></span>
									</button>
								</form>

								<!-- Delete Book -->
								<form action="{% url 'books:delete_book' book.id %}" method="post" style="display: inline;">
									{% csrf_token %}
									<input type="hidden" name="book_id" value="{{ book.id }}" />
									<button type="submit" class="btn btn-default btn-sm">
										<span class="glyphicon glyphicon-trash"></span>
									</button>
								</form>


							</div>
						</div>
					</center>
				</div>
			{% endif %}
			{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
		{% endfor %}
    </div>
</div>

<center>
	<div class="col-sm-12">
		<br>
		<a href="{% url 'books:create_book' %}">
			<button type="button" class="btn btn-success">
				<span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Book
			</button>
		</a>
	</div>
</center>

{% endblock %}

books/templates/books/login.html
{% extends 'books/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-6 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'books:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'books:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h4>What is Noodle?</h4>
                        <p>Noodle is an Intra-Campus Online Book Portal where students can buy and sell books with any hassle.</p><br>

                        <h4>How to use Noodle?</h4>
                        <p>Noodle is a very intuitive, user-friendly and easy-to-use Web Application. Just register, sign-in, add a book(s) you want to sell and/or use the search bar to search for a book you want to buy that might be for sale.</p>
                    </div>
                </div>   
        </div>
    </div>

</div>

{% endblock %}

books/templates/books/user_form.html
{% extends 'books/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-6 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'books/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'books:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h4>What is Noodle?</h4>
                        <p>Noodle is an Intra-Campus Online Book Portal where students can buy and sell books with any hassle.</p><br>

                        <h4>How to use Noodle?</h4>
                        <p>Noodle is a very intuitive, user-friendly and easy-to-use Web Application. Just register, sign-in, add a book(s) you want to sell and/or use the search bar to search for a book you want to buy that might be for sale.</p>
                    </div>
                </div>   
        </div>
    </div>

</div>

{% endblock %}